name: chicken_reciper
description: Discover delicious chicken recipes with step-by-step cooking instructions, timers, and shopping lists.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  
  wakelock_plus: ^1.2.8         
  share_plus: ^10.0.3           
  audioplayers: ^6.1.0           
  introduction_screen: ^3.1.14   
  uuid: ^4.5.1                   
  webview_flutter: ^4.13.1      
  image_picker: ^1.1.2           
  path_provider: ^2.1.4         

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/
